### ISSUE TITLE
`screen /dev/ttyUSB0 115200` fails with `[screen is terminating]`

### ISSUE THREAD

**Issue by brianthelion** [f0cal/google-coral#2]
* Doc you were trying to follow: https://coral.withgoogle.com/tutorials/devboard/
* Your host OS: Ubuntu 18.04
* Your Python3 version: 3.6.7

# What I ran

When running the Getting Started tutorial, I everything went smoothly up to:

```bash
$ dmesg | grep ttyUSB
[11567.500409] usb 1-2: cp210x converter now attached to ttyUSB0
[11567.503236] usb 1-2: cp210x converter now attached to ttyUSB1
[11569.062428] cp210x ttyUSB1: failed set req 0x1e size 4 status: -32
[11569.062443] cp210x ttyUSB1: failed to set baud rate to 300
```
and then
```bash
$ screen /dev/ttyUSB0 115200
```

# What the docs said should happen

"Terminal should go blank."

# What actually happened

```bash
$ screen /dev/ttyUSB0 115200
[screen is terminating]
```

**Comment by brianthelion** [comment]
Not sure what's up with the `dmesg` output but I think it's orthogonal to the `screen` issue. The `screen` issue I believe is due to `udev` permissions. It's quickly solved with:
```bash
$ sudo screen /dev/ttyUSB0 115200
```

**Comment by hughpyle** [comment]
Alternatively: the /dev/ttyUSB0 should be group-writeable bu 'dialout', so add your user to the 'dialout' group:  
```
sudo usermod -a -G dialout $USER
```
then you'll be able to run screen without sudo.

**Comment by taunusflieger** [comment]
Are you trying to connect from within a VM? Got the same when using a Parallel VM. I ended up using a Raspberry PI as the Linux box for installation

**Comment by brianthelion** [comment]
No, I was connecting from a Thinkpad running Ubuntu.

**Comment by asnare** [comment]
When getting started there are two USB devices that are used:

 - The first is a UART bridge that you use get the serial console. This is normally `/dev/ttyUSB0` after you plug it in.
 - The second is the OTG/data port where the firmware gets uploaded. The `udev` rule in the documentation (covering device with vendor id `0525`) ensures this gets the right permissions for `fastboot` to do its thing.

Unfortunately there's no `udev` rule for the first (terminal) device (vendor id `10c4`) which means that screen probably can't open it.

I fixed this by adding an additional rule to cover the first device, after which my `/etc/udev/65-edgetpu-board.rules` file looked like this:
```
SUBSYSTEMS=="usb",ATTRS{idVendor}=="10c4",MODE="0664",GROUP="plugdev",TAG+="uaccess"
SUBSYSTEMS=="usb",ATTRS{idVendor}=="0525",MODE="0664",GROUP="plugdev",TAG+="uaccess"
```
Note that there's also a difference from the docs here in that these lines start with SUBSYSTEM**S** instead of SUBSYSTEM.

With this minor change the rest of the QuickStart worked for me.

Setup: Debian 9.8 (VM) on a macOS Host (Virtualised via VMWare Fusion with USB 3.0 passthrough)

**Comment by racky1** [comment]
So I had this problem when using an Ubuntu box so I used a Raspberry Pi 3 and was able to flash the unit with the instructions.

**Comment by BarryLYH** [comment]
> Alternatively: the /dev/ttyUSB0 should be group-writeable by 'dialout', so add your user to the 'dialout' group:
> 
> ```
> sudo usermod -a -G dialout $USER
> ```
> then you'll be able to run screen without sudo.

I tried it and now I can connect to ttyUSB0. However, when I went to step "fastboot devices", I cannot find the ttyUSB1. Do you have any idea of that?

**Comment by Namburger** [comment]
@BarryLYH you shouldn't need both `/dev/ttyUSB0` and `/dev/ttyUSB1`, could you clarify?

**Comment by TruckDynasty** [comment]
For anyone winding up here from a search engine: you generally need to add your user to both 'dialout' *and* 'tty'

**Comment by phnjau** [comment]
My problem is that i get into the serial port and it gives me a bunch of question marks and I can't  even type anything and what supposed to do is type "AT".Do you think any of you guys can give me some tips?


Thanks

**Comment by SantoshGovindaraj** [comment]
I had similar issue. I solved it by checking permissions of the port.
```
sudo usermod -aG dialout $USER
sudo chmod 666 /dev/ttyUSB0
```

**Comment by phnjau** [comment]
Ok thanks ill try that.
